version: '3.7'
services:

##
# Web application
#
  company-cob-web:
    build: 
      context: ./web/
    hostname: 'company-cob-web'
    container_name: 'company-cob-web'
    environment:
      - SPRING_BOOT_ADMIN_URL=http://company-cob-spring-boot-admin:8081
      - DB_HOST=company-cob-postgre-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=companycob
      - APPLICATION_SECURITY_USER=companycob
      - APPLICATION_SECURITY_PASSWORD=companycob
      - APPLICATION_PORT=9090
      - LIQUIBASE_ENABLED=true
      - REDIS_HOST=company-cob-redis
      - REDIS_PORT=6379
      - REDIS_TIME_TO_LIVE=20000
      - CONTRACT_CACHE_TTL=60
    ports:
      - '9090:9090'
    networks: 
      - companycobnet
    depends_on: 
      - company-cob-spring-boot-admin
      - company-cob-postgre-database
      - company-cob-redis

##
# SpringBoot Admin
#
  company-cob-spring-boot-admin:
    build:
      context: ./spring-boot-admin/
    hostname: 'company-cob-spring-boot-admin'
    container_name: 'company-cob-spring-boot-admin'
    environment:
      - APPLICATION_PORT=8081
      - SBA_LOGIN_USERNAME=companycob
      - SBA_LOGIN_PASSWORD=companycob
    ports:
      - '8081:8081'
    networks:
      - companycobnet
      
##
# Postgre database
#
  company-cob-postgre-database:
    image: postgres:13-alpine
    hostname: 'company-cob-postgre-database'
    container_name: 'company-cob-postgre-database'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=companycob
    networks:
      - companycobnet

  company-cob-redis:
    image: redis:5.0.3
    hostname: 'company-cob-redis'
    container_name: 'company-cob-redis'
    ports:
      - '6379:6379'
    networks:
      - companycobnet

networks: 
  companycobnet: 