logging:
  level:
    org:
      hibernate: INFO
      springframework:
        web: INFO
  file: company-cob-web.log

server:
  port: 9000
  servlet:
    context-path: 

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/companycob
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
application:
  security:
    user: companycob
    password: companycob 
