spring.application.name: company-cob-web
logging.level.root: INFO
logging.file.name: company-cob-web.log

server.port: ${APPLICATION_PORT:9090}
server.servlet.context-path: 

spring.datasource.url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:companycob}
spring.datasource.driverClassName: org.postgresql.Driver
spring.datasource.username: ${DB_USERNAME:postgres}
spring.datasource.password: ${DB_PASSWORD:password}

spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: false
spring.jpa.hibernate.ddl-auto: none

management.endpoints.web.exposure.include: "*"

spring.boot.admin.client.username: ${APPLICATION_SECURITY_USER:companycob}
spring.boot.admin.client.password: ${APPLICATION_SECURITY_PASSWORD:companycob}
spring.boot.admin.client.instance.metadata.user.name: ${spring.boot.admin.client.username}
spring.boot.admin.client.instance.metadata.user.password: ${spring.boot.admin.client.password}
spring.boot.admin.client.url: ${SPRING_BOOT_ADMIN_URL:http://localhost:8081}
spring.boot.admin.client.instance.prefer-ip: true

spring.liquibase.change-log: classpath:db/db.changelog-master.xml
spring.liquibase.enabled: ${LIQUIBASE_ENABLED:true}