name: check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Clean
        run: ./mvnw -B clean

      - name: Compile
        run: ./mvnw -B compile -DskipTests

      - name: Test
        run: ./mvnw -B test

      - name: Generate Jacoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v1.0.0
        with:
          jacoco-csv-file: build-tools/target/site/jacoco/jacoco.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

      - name: Create pull request
        if: ${{ github.event_name == 'push' }}
        uses: peter-evans/create-pull-request@v3.4.1
        with:
          title: "Autogenerated Jacoco Coverage Badge"
          body: >
            Autogenerated Jacoco coverage badge, generated by
            the [jacoco-badge-generator](https://github.com/cicirello/jacoco-badge-generator)
            GitHub action.
          commit-message: "Autogenerated Jacoco Coverage Badge"
          branch: create-pull-request/badge
          delete-branch: true

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: build-tools/target/site/jacoco/