server.port: ${APPLICATION_PORT:8081}
spring.boot.admin.login.username: ${SBA_LOGIN_USERNAME:companycob}
spring.boot.admin.login.password: ${SBA_LOGIN_PASSWORD:companycob}

spring.devtools.livereload.port: 0